---
stages:
  - build
  - lint

variables:
  DOCKER_TLS_CERTDIR: ""

####################################################
# BUILD STAGE
####################################################

build_lint_image:
  stage: build
  tags:
    - docker
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - >
      echo '{
        "auths": {
          "$CI_REGISTRY": {
            "username": "$CI_REGISTRY_USER",
            "password": "$CI_REGISTRY_PASSWORD"
          }
        }
      }' > /kaniko/.docker/config.json
    - |
      DEST_BASE="${CI_REGISTRY_IMAGE}"
      DESTINATION_ARGS="--destination ${DEST_BASE}:lint"
      DESTINATION_ARGS="${DESTINATION_ARGS} \
        --destination ${DEST_BASE}:${CI_COMMIT_SHA}"
      DESTINATION_ARGS="${DESTINATION_ARGS} \
        --destination ${DEST_BASE}:latest"
      if [ -n "${CI_COMMIT_TAG}" ]; then
        DESTINATION_ARGS="${DESTINATION_ARGS} \
          --destination ${DEST_BASE}:${CI_COMMIT_TAG}"
      fi
    - >
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      ${DESTINATION_ARGS}
      --build-arg BUILDPLATFORM=linux/amd64
      --build-arg TARGETPLATFORM=linux/amd64
  rules:
    - changes:
        - Dockerfile
        - .gitlab-ci.yml

####################################################
# LINT STAGE
####################################################

lint:
  stage: lint
  tags:
    - docker
  image: $CI_REGISTRY_IMAGE:lint
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  cache:
    paths:
      - ${PRE_COMMIT_HOME}
  script:
    - pre-commit run --all-files
